# node-hello/argo-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-hello
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vinay17-arch/practical_task.git'
    targetRevision: HEAD
    path: charts/node-hello
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
