apiVersion: v1
kind: Service
metadata:
  name: node-hello-service
  labels:
    app: node-hello
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: node-hello
